return { {
    "ThePrimeagen/harpoon",
    config = function()
        local mark = require("harpoon.mark")
        local ui = require("harpoon.ui")

        _G.nmap("<leader>a", mark.add_file, { desc = "[A] buffer to harpoon" })
        _G.nmap("<a-e>", ui.toggle_quick_menu, { desc = "View added buffers in harpoon" })
        _G.nmap("<a-v>", ui.toggle_quick_menu, { desc = "[V]iew added buffers in harpoon" })
        _G.nmap("<leader>1", function()
            ui.nav_file(1)
        end)
        _G.nmap("<leader>2", function()
            ui.nav_file(2)
        end)
        _G.nmap("<leader>3", function()
            ui.nav_file(3)
        end)
        _G.nmap("<leader>4", function()
            ui.nav_file(4)
        end)
        _G.nmap("<leader>5", function()
            ui.nav_file(5)
        end)
        _G.nmap("<leader>6", function()
            ui.nav_file(6)
        end)
        _G.nmap("<leader>7", function()
            ui.nav_file(7)
        end)
    end,
} }
