[colors.primary]
background = '#062D93'
foreground = '#E9E2E0'

[colors.cursor]
text = '#E9E2E0'
cursor = '#6E82A6'

[colors.normal]
black = '#C1B7B4'
red = '#B4B88C'
green = '#C1A3AA'
yellow = '#7EABB3'
blue = '#C69A69'
magenta = '#7B90CA'
cyan = '#CD7374'
white = '#6C6F54'

[colors.bright]
black = '#A8AC82'
red = '#F0F6BA'
green = '#FDD2DC'
yellow = '#A8E4EF'
blue = '#F1A752'
magenta = '#7EA0FA'
cyan = '#FF787B'
white = '#EFF2D4'
