[colors.primary]
background = '#121210'
foreground = '#B0B0AD'

[colors.cursor]
text = '#B0B0AD'
cursor = '#B0B0AD'

[colors.normal]
black = '#3F3F3D'
red = '#CE3A91'
green = '#3A7DCE'
yellow = '#989B00'
blue = '#2F8D5F'
magenta = '#9E543D'
cyan = '#4B4B45'
white = '#868681'

[colors.bright]
black = '#5E5E5A'
red = '#FF0096'
green = '#0D7CFF'
yellow = '#CBCF00'
blue = '#00994F'
magenta = '#BF5C3E'
cyan = '#515149'
white = '#868681'
