[colors.primary]
background = '#0E0E0C'
foreground = '#B0AFAC'

[colors.cursor]
text = '#B0AFAC'
cursor = '#B0AFAC'

[colors.normal]
black = '#3B3A39'
red = '#FF0096'
green = '#0075FF'
yellow = '#CBCF00'
blue = '#00994F'
magenta = '#B23A3F'
cyan = '#504F48'
white = '#858581'

[colors.bright]
black = '#5D5D5A'
red = '#FF0096'
green = '#0075FF'
yellow = '#CBCF00'
blue = '#00994F'
magenta = '#B23A3F'
cyan = '#504F48'
white = '#858581'
