live_config_reload = true

[env]
TERM = "alacritty"

[window]
dimensions = { columns = 100, lines = 35 }
opacity = 0.95
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
startup_mode = "windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
resize_increments = false
# option_as_alt = "OnlyLeft"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
offset = { x = 0, y = 0 }          
# glypth_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
primary = { background = '0x0c0c16', foreground = '0xd8dee9'}
normal = {black = '0x2c2c3d', red = '0xff6e6e', green = '0x9ec875', yellow = '0xffa759', blue = '0x70a7d4', magenta = '0xd291e0', cyan = '0x96e0e0', white = '0xd8dee9' }
bright = { black = '0x414166', red = '0xff8d8d', green = '0xb3d987', yellow = '0xffc57f', blue = '0x9bb3d3', magenta = '0xffa1ff', cyan = '0x9cd8d8', white = '0xffffff' }
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
