import = [
    # "~/.dotfiles/alacritty/themes/bamboo.toml",
    # "~/.config/alacritty/themes/catppuccin-latte.toml",
    # "~/.config/alacritty/themes/catppuccin-frappe.toml",
    "~/.config/alacritty/themes/catppuccin-macchiato.toml",
    # "~/.config/alacritty/theme/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
# TERM = "xterm-256color"
TERM = "alacritty"

[window]
dimensions = { columns = 120, lines = 35 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.98
blur = true
startup_mode = "windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
resize_increments = false

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12
offset = { x = 0, y = 0 }
# glypth_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"
