live_config_reload = true

[env]
TERM = "alacritty"

[window]
dimensions = { colums = 100, lines = 35 }
padding = { x = 10, y = 10 }
dynamic_padding = true
decorations = "None"
opacity = 0.95
startup_mode = "windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decoration_theme_variant = "None"
resize_increments = false
option_as_alt = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { stye = "Bold" }
italic = { stye = "Italic" }
bold_italic = { stye = "Bold Italic" }
size = 12
offset = { x = 0, y = 0 }                                 #Offset is the extra space around each character. _y_ can be thought of as
#modifying the line spacing, and _x_ as modifying the letter spacing.
glypth_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[colors]
primary = { foreground = "#d8d8d8", background = "#181818", dim_foreground = "#828482", bright_foreground = "None" }
# bright_forefround is only used when _draw\_bold\_text\_with\_bright\_colors_ is
# _true_.
# If this is not set, the normal foreground will be used.

# Allowed values are hexadecimal colors like _#ff00ff_, or
# _CellForeground_/_CellBackground_, which references the affected cell.
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
