# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
quit = ['q', 'esc', 'ctrl+c']
# movement
list_up = ['up', 'k']
list_down = ['down', 'j']
page_up = ['pgup', '']
page_down = ['pgdown', '']
# file panel control
create_new_file_panel = ['n', '']
close_file_panel = ['w', '']
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+tab', 'H']
toggle_file_preview_panel = ['f', '']
open_sort_options_menu = ['o', '']
toggle_reverse_sort = ['R', '']
# change focus
focus_on_process_bar = ['ctrl+p']
focus_on_sidebar = ['s', 'u', 'ctrl+r', 'ctlr+s', 'ctlr+f']
focus_on_metadata = ['ctrl+m', 'm']
# create file/directory and rename
file_panel_item_create = ['a', '']
file_panel_item_rename = ['r', '']
# file operations
copy_items = ['y', '']
cut_items = ['x', '']
paste_items = ['p', '']
delete_items = ['d', '']
# compress and extract
extract_file = ['ctrl+e', '']
compress_file = ['ctrl+a', '']
# editor
open_file_with_editor = ['e', '']
open_current_directory_with_editor = ['E', '']
# other
pinned_directory = ['I', '']
toggle_dot_file = ['.', '']
change_panel_mode = ['v']
open_help_menu = ['?', '']
open_command_line = [':', '']
copy_path = ['Y', '']
copy_present_working_directory = ['c', '']
toggle_footer = ['ctrl+h']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter', '']
cancel_typing = ['alt+e', 'esc', 'ctrl+c', 'alt+i']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', 'backspace', '=']
search_bar = ['/', '']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['A', '']
