$wallpapr = /home/umbrelluck/Pictures/Wallhaven/wallhaven-7pd9w3.jpg
$background = rgb(062D93)
$foreground = rgb(E9E2E0)
$color0 = rgb(C1B7B4)
$color1 = rgb(B4B88C)
$color2 = rgb(C1A3AA)
$color3 = rgb(7EABB3)
$color4 = rgb(C69A69)
$color5 = rgb(7B90CA)
$color6 = rgb(CD7374)
$color7 = rgb(6C6F54)
$color8 = rgb(A8AC82)
$color9 = rgb(F0F6BA)
$color10 = rgb(FDD2DC)
$color11 = rgb(A8E4EF)
$color12 = rgb(F1A752)
$color13 = rgb(7EA0FA)
$color14 = rgb(FF787B)
$color15 = rgb(EFF2D4)
